In [1]:
import pandas as pd
df = pd.read_csv('house_prices.csv')

In [2]:
df.head()

,Title,Sub_title,Price,Address,Baths,Land size,Beds,House size,Location,Description,Post_URL,Seller_name,Seller_type,published_date,Geo_Address,Lat,Lon
0,House with Land for Sale in Matara for sale,"Posted on 06 Nov 2:32 pm, Matara City, Matara","Rs 5,400,000","Gangodagama Roard,Hakmana,Matara.",1,50.0 perches,3,"1,600.0 sqft","Matara City, Matara","Land for sale with house Matara,Hakmana Gangod...",https://ikman.lk/en/ad/house-with-land-for-sal...,Ishara Dilshan,Member,2021-11-06 14:32,"Matara City, Matara, Sri Lanka",80.500000,6.166670
1,à¶ à¶½à·à¶­à· à¶à·à¶¸à¶» 3 à¶ à¶à·à· à...,"Posted on 24 Oct 7:27 am, Athurugiriya, Colombo","Rs 16,800,000",Athurugiriya Galwarusapare,3,8.0 perches,3,"1,480.0 sqft","Athurugiriya, Colombo",*House For Sale In Athurugiriya *Galwarusapare...,https://ikman.lk/en/ad/alut-kaamr-3-k-grh-bhaa...,DILRUWAN REAL ESTATE,Premium-Member,2021-10-24 07:27,"Athurugiriya, Colombo, Sri Lanka",79.989929,6.877246
2,Kelaniya - House on 20P Land for sale for sale,"Posted on 17 Nov 5:19 pm, Kelaniya, Gampaha","Rs 20,000,000",Kelaniya- Ranaviru Maldeniya Road,2,20.0 perches,3,"2,800.0 sqft","Kelaniya, Gampaha","Kelaniya- Biyagama road, Ranaviru Maladeniya R...",https://ikman.lk/en/ad/kelaniya-house-on-20p-l...,Provident Paradise (Pvt) Ltd,Member,2021-11-17 17:19,"Kelaniya, Gampaha, Sri Lanka",79.914926,6.951178
3,House For Sale in Pamankada Lane Wellawatte Co...,"Posted on 17 Nov 5:07 pm, Colombo 6, Colombo","Rs 187,000,000",Pamankada Lane Wellawatte Colombo.06,5,22.0 perches,5,"4,000.0 sqft","Colombo 6, Colombo",22 Perches House For Sale in Pamankada Lane We...,https://ikman.lk/en/ad/house-for-sale-in-paman...,Colombo Construction Property Developers,Premium-Member,2021-11-17 17:07,"Colombo 6, Colombo, Sri Lanka",80.016670,6.866670
4,House For Sale - Attidiya for sale,"Posted on 17 Nov 5:06 pm, Dehiwala, Colombo","Rs 1,300,000",MainRoad Attidiya,1,6.3 perches,2,900.0 sqft,"Dehiwala, Colombo",*à¶ à¶­à·à¶­à·à¶©à·à¶º à¶´à·âà¶»à¶¯à·à·...,https://ikman.lk/en/ad/house-for-sale-attidiya...,Lakdinu Houses,Member,2021-11-17 17:06,"Dehiwala, Colombo, Sri Lanka",79.880242,6.838232

In [3]:
relevant_columns = ['Title','Price','Location', 'Baths', 'Beds','House size', 'published_date']
df1 = df[relevant_columns]

In [4]:
df1.head()

,Title,Price,Location,Baths,Beds,House size,published_date
0,House with Land for Sale in Matara for sale,"Rs 5,400,000","Matara City, Matara",1,3,"1,600.0 sqft",2021-11-06 14:32
1,à¶ à¶½à·à¶­à· à¶à·à¶¸à¶» 3 à¶ à¶à·à· à...,"Rs 16,800,000","Athurugiriya, Colombo",3,3,"1,480.0 sqft",2021-10-24 07:27
2,Kelaniya - House on 20P Land for sale for sale,"Rs 20,000,000","Kelaniya, Gampaha",2,3,"2,800.0 sqft",2021-11-17 17:19
3,House For Sale in Pamankada Lane Wellawatte Co...,"Rs 187,000,000","Colombo 6, Colombo",5,5,"4,000.0 sqft",2021-11-17 17:07
4,House For Sale - Attidiya for sale,"Rs 1,300,000","Dehiwala, Colombo",1,2,900.0 sqft,2021-11-17 17:06

In [6]:
column_name = 'Price'
data_type = df[column_name].dtype
data_type

dtype('O')

In [7]:
df1

,Title,Price,Location,Baths,Beds,House size,published_date
0,House with Land for Sale in Matara for sale,"Rs 5,400,000","Matara City, Matara",1,3,"1,600.0 sqft",2021-11-06 14:32
1,à¶ à¶½à·à¶­à· à¶à·à¶¸à¶» 3 à¶ à¶à·à· à...,"Rs 16,800,000","Athurugiriya, Colombo",3,3,"1,480.0 sqft",2021-10-24 07:27
2,Kelaniya - House on 20P Land for sale for sale,"Rs 20,000,000","Kelaniya, Gampaha",2,3,"2,800.0 sqft",2021-11-17 17:19
3,House For Sale in Pamankada Lane Wellawatte Co...,"Rs 187,000,000","Colombo 6, Colombo",5,5,"4,000.0 sqft",2021-11-17 17:07
4,House For Sale - Attidiya for sale,"Rs 1,300,000","Dehiwala, Colombo",1,2,900.0 sqft,2021-11-17 17:06
...,...,...,...,...,...,...,...
15322,House for sale Nittabuwa for sale,"Rs 6,750,000","Nittambuwa, Gampaha",1,3,"1,200.0 sqft",2021-11-23 14:06
15323,House for Sale - Wellawatte for sale,"Rs 70,000,000","Dehiwala, Colombo",2,3,"1,100.0 sqft",2021-11-19 21:08
15324,House with 20 Perches Land - Maharagama for sale,"Rs 44,000,000","Maharagama, Colombo",4,5,"2,750.0 sqft",2021-11-29 00:26
15325,House for sale in Maharagama for sale,"Rs 15,000,000","Dehiwala, Colombo",2,2,"1,350.0 sqft",2021-11-19 21:12
15326,Mount Lavinia House for Sale for sale,"Rs 58,000,000","Colombo 6, Colombo",5,7,"5,000.0 sqft",2021-11-24 18:52

In [8]:
df1 = df1.dropna()

In [9]:
df1

,Title,Price,Location,Baths,Beds,House size,published_date
0,House with Land for Sale in Matara for sale,"Rs 5,400,000","Matara City, Matara",1,3,"1,600.0 sqft",2021-11-06 14:32
1,à¶ à¶½à·à¶­à· à¶à·à¶¸à¶» 3 à¶ à¶à·à· à...,"Rs 16,800,000","Athurugiriya, Colombo",3,3,"1,480.0 sqft",2021-10-24 07:27
2,Kelaniya - House on 20P Land for sale for sale,"Rs 20,000,000","Kelaniya, Gampaha",2,3,"2,800.0 sqft",2021-11-17 17:19
3,House For Sale in Pamankada Lane Wellawatte Co...,"Rs 187,000,000","Colombo 6, Colombo",5,5,"4,000.0 sqft",2021-11-17 17:07
4,House For Sale - Attidiya for sale,"Rs 1,300,000","Dehiwala, Colombo",1,2,900.0 sqft,2021-11-17 17:06
...,...,...,...,...,...,...,...
15322,House for sale Nittabuwa for sale,"Rs 6,750,000","Nittambuwa, Gampaha",1,3,"1,200.0 sqft",2021-11-23 14:06
15323,House for Sale - Wellawatte for sale,"Rs 70,000,000","Dehiwala, Colombo",2,3,"1,100.0 sqft",2021-11-19 21:08
15324,House with 20 Perches Land - Maharagama for sale,"Rs 44,000,000","Maharagama, Colombo",4,5,"2,750.0 sqft",2021-11-29 00:26
15325,House for sale in Maharagama for sale,"Rs 15,000,000","Dehiwala, Colombo",2,2,"1,350.0 sqft",2021-11-19 21:12
15326,Mount Lavinia House for Sale for sale,"Rs 58,000,000","Colombo 6, Colombo",5,7,"5,000.0 sqft",2021-11-24 18:52

In [10]:
colombo_region = df1[df['Location'].str.contains('Colombo')]
colombo_region

,Title,Price,Location,Baths,Beds,House size,published_date
1,à¶ à¶½à·à¶­à· à¶à·à¶¸à¶» 3 à¶ à¶à·à· à...,"Rs 16,800,000","Athurugiriya, Colombo",3,3,"1,480.0 sqft",2021-10-24 07:27
3,House For Sale in Pamankada Lane Wellawatte Co...,"Rs 187,000,000","Colombo 6, Colombo",5,5,"4,000.0 sqft",2021-11-17 17:07
4,House For Sale - Attidiya for sale,"Rs 1,300,000","Dehiwala, Colombo",1,2,900.0 sqft,2021-11-17 17:06
5,House For Sale in Batharamulle for sale,"Rs 55,000,000","Talawatugoda, Colombo",4,4,"3,300.0 sqft",2021-11-17 17:04
7,House for Sale in Kesbewa for sale,"Rs 16,700,000","Piliyandala, Colombo",3,3,"1,400.0 sqft",2021-11-17 16:56
...,...,...,...,...,...,...,...
15320,Single Storey Modern House For Sale In Thalawa...,"Rs 16,500,000","Talawatugoda, Colombo",3,3,"2,300.0 sqft",2021-11-23 11:14
15323,House for Sale - Wellawatte for sale,"Rs 70,000,000","Dehiwala, Colombo",2,3,"1,100.0 sqft",2021-11-19 21:08
15324,House with 20 Perches Land - Maharagama for sale,"Rs 44,000,000","Maharagama, Colombo",4,5,"2,750.0 sqft",2021-11-29 00:26
15325,House for sale in Maharagama for sale,"Rs 15,000,000","Dehiwala, Colombo",2,2,"1,350.0 sqft",2021-11-19 21:12
15326,Mount Lavinia House for Sale for sale,"Rs 58,000,000","Colombo 6, Colombo",5,7,"5,000.0 sqft",2021-11-24 18:52

In [11]:
# Remove non-numeric characters and convert to float
# colombo_region['Price'] = colombo_region['Price'].str.replace('Rs ', '').str.replace(',', '').astype('float32')
colombo_region['Price'] = colombo_region['Price'].str.replace('Rs ', '').str.replace(',', '')

<ipython-input-11-fc7176ad9820>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colombo_region['Price'] = colombo_region['Price'].str.replace('Rs ', '').str.replace(',', '')

In [12]:
column_name = 'Price'
data_type = df[column_name].dtype
data_type

dtype('O')

In [13]:
colombo_region.head()

,Title,Price,Location,Baths,Beds,House size,published_date
1,à¶ à¶½à·à¶­à· à¶à·à¶¸à¶» 3 à¶ à¶à·à· à...,16800000,"Athurugiriya, Colombo",3,3,"1,480.0 sqft",2021-10-24 07:27
3,House For Sale in Pamankada Lane Wellawatte Co...,187000000,"Colombo 6, Colombo",5,5,"4,000.0 sqft",2021-11-17 17:07
4,House For Sale - Attidiya for sale,1300000,"Dehiwala, Colombo",1,2,900.0 sqft,2021-11-17 17:06
5,House For Sale in Batharamulle for sale,55000000,"Talawatugoda, Colombo",4,4,"3,300.0 sqft",2021-11-17 17:04
7,House for Sale in Kesbewa for sale,16700000,"Piliyandala, Colombo",3,3,"1,400.0 sqft",2021-11-17 16:56

In [14]:
import tensorflow as tf
from tensorflow import keras

In [33]:
X = colombo_region[['Baths','Beds']] #the features that I am using
y = colombo_region['Price'] # the target variable

In [34]:
#for the normalization part
X_norm = (X - X.mean()) / X.std()

<ipython-input-34-958b7ae7486b>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  X_norm = (X - X.mean()) / X.std()
<ipython-input-34-958b7ae7486b>:2: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  X_norm = (X - X.mean()) / X.std()

In [41]:
X_norm = X_norm.astype('float32')
y = y.astype('float32')

In [42]:
#building the model
model = keras.Sequential([
    keras.layers.Dense(32, activation = 'relu', input_shape =(2,)),
    keras.layers.Dense(32, activation= 'relu'),
    keras.layers.Dense(1)
])

In [43]:
model.compile(optimizer='adam', loss='mean_squared_error')

In [44]:
model.fit(X_norm, y, epochs=100, batch_size=32)

Epoch 1/100
344/344 [==============================] - 1s 2ms/step - loss: nan
Epoch 2/100
344/344 [==============================] - 1s 2ms/step - loss: nan
Epoch 3/100
344/344 [==============================] - 1s 2ms/step - loss: nan
Epoch 4/100
344/344 [==============================] - 1s 2ms/step - loss: nan
Epoch 5/100
344/344 [==============================] - 1s 2ms/step - loss: nan
Epoch 6/100
344/344 [==============================] - 1s 2ms/step - loss: nan
Epoch 7/100
344/344 [==============================] - 1s 2ms/step - loss: nan
Epoch 8/100
344/344 [==============================] - 1s 2ms/step - loss: nan
Epoch 9/100
344/344 [==============================] - 1s 2ms/step - loss: nan
Epoch 10/100
344/344 [==============================] - 1s 2ms/step - loss: nan
Epoch 11/100
344/344 [==============================] - 1s 2ms/step - loss: nan
Epoch 12/100
344/344 [==============================] - 1s 2ms/step - loss: nan
Epoch 13/100
344/344 [==============================] - 1s 2ms/step - loss: nan
Epoch 14/100
344/344 [==============================] - 1s 2ms/step - loss: nan
Epoch 15/100
 34/344 [=>............................] - ETA: 0s - loss: nan

KeyboardInterrupt: ignored

In [ ]:
test_data = pd.DataFrame({'bedrooms': [3, 4], 'bathrooms': [2, 3]})
normalized_test_data = (test_data - X.mean()) / X.std()
predictions = model.predict(normalized_test_data)

1/1 [==============================] - 0s 95ms/step

<ipython-input-66-92fd7bfa72ce>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  normalized_test_data = (test_data - X.mean()) / X.std()
<ipython-input-66-92fd7bfa72ce>:2: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  normalized_test_data = (test_data - X.mean()) / X.std()

In [ ]:
predictions = predictions.astype('float64')
print(predictions)

[[nan]
 [nan]]

In [ ]:
# Calculate the errors (difference between predictions and actual prices)
errors = y - predictions.flatten()

ValueError: ignored